# Generated by Django 6.0.2 on 2026-02-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('favorite_genres', models.JSONField(default=list)),
                ('excluded_genres', models.JSONField(default=list)),
                ('viewed_movies', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('overview', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(db_index=True)),
                ('vote_count', models.IntegerField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('genres', models.JSONField(default=list)),
                ('cast', models.JSONField(default=list)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('mood_happy', models.FloatField(db_index=True, default=0)),
                ('mood_sad', models.FloatField(db_index=True, default=0)),
                ('mood_excited', models.FloatField(db_index=True, default=0)),
                ('mood_scared', models.FloatField(db_index=True, default=0)),
                ('mood_romantic', models.FloatField(db_index=True, default=0)),
                ('mood_thoughtful', models.FloatField(db_index=True, default=0)),
                ('mood_adventurous', models.FloatField(db_index=True, default=0)),
                ('mood_relaxed', models.FloatField(db_index=True, default=0)),
                ('mood_mysterious', models.FloatField(db_index=True, default=0)),
                ('mood_inspired', models.FloatField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-vote_average', '-vote_count'],
                'indexes': [models.Index(fields=['vote_average', 'vote_count'], name='Moodflix_mo_vote_av_2ac27b_idx'), models.Index(fields=['popularity'], name='Moodflix_mo_popular_2cbac9_idx')],
            },
        ),
    ]
