# Generated by Django 6.0.2 on 2026-04-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moodflix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_path',
        ),
    ]
